CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS pets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(32) NOT NULL,
  species VARCHAR(32) NOT NULL DEFAULT 'blob',
  color VARCHAR(32) NOT NULL DEFAULT 'green',
  rank_tier VARCHAR(16) NOT NULL DEFAULT 'IRON',
  rank_division SMALLINT NOT NULL DEFAULT 4,
  lp SMALLINT NOT NULL DEFAULT 0,
  cs INTEGER NOT NULL DEFAULT 10,
  positioning INTEGER NOT NULL DEFAULT 10,
  skillshots INTEGER NOT NULL DEFAULT 10,
  dodge INTEGER NOT NULL DEFAULT 10,
  combat INTEGER NOT NULL DEFAULT 10,
  mechanics INTEGER NOT NULL DEFAULT 10,
  vision INTEGER NOT NULL DEFAULT 10,
  objectives INTEGER NOT NULL DEFAULT 10,
  rotations INTEGER NOT NULL DEFAULT 10,
  wave_control INTEGER NOT NULL DEFAULT 10,
  decision_making INTEGER NOT NULL DEFAULT 10,
  stamina INTEGER NOT NULL DEFAULT 100,
  stress INTEGER NOT NULL DEFAULT 0,
  luck INTEGER NOT NULL DEFAULT 50,
  xp INTEGER NOT NULL DEFAULT 0,
  coins INTEGER NOT NULL DEFAULT 100,
  next_ranked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ranked_matches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pet_id UUID NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finishes_at TIMESTAMPTZ NOT NULL,
  result VARCHAR(16),
  lp_delta SMALLINT,
  xp_delta INTEGER,
  coins_delta INTEGER,
  simulation JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS pets_next_ranked_idx ON pets(next_ranked_at);
CREATE INDEX IF NOT EXISTS ranked_matches_pet_idx ON ranked_matches(pet_id, created_at DESC);